### ISSUE TITLE
feat: pin visualization should reflect the current pin state

### ISSUE THREAD

**Issue by fourcube** [fourcube/spidev#3]
## current
Currently a pin only changes its visualization when it is selected (clicked) by the user. It gets a dark drop shadow. 

## should
A pin should reflect all of it's state variables in its visualization. E.g. through little symbols or letters. 

`id` - the physical id of the pin; currently displayed as a centered number
`direction` - not displayed; 
`value` - not displayed;
`resistor` - not displayed;

- [x] make the pins display as a square
- [x] make background ~~grey~~ green for pins with value 1  
- [x] make background transparent for pins with value 0
- [x] put "I" (capital i) in top right corner when pin is has "direction" == "IN"
- [x] put "O"  in top right corner when pin is has "direction" == "OUT"
- [x] put "U" in bottom right corner when pin is has "resistor" == "PULL_UP"
- [x] put "D" in bottom right corner when pin is has "resistor" == "PULL_DOWN"

**Comment by dirk-rossbach** [comment]
done
